# Generated by Django 2.1.5 on 2019-01-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=25, unique=True)),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('match_played', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('amount_won', models.IntegerField(default=0)),
            ],
        ),
    ]
