# Generated by Django 2.1.3 on 2019-01-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20190121_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
