# Generated by Django 2.1.3 on 2019-01-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_userprofileinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='entry',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
