# Generated by Django 2.1.5 on 2019-01-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_match_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='pay',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
