# Generated by Django 2.1.5 on 2019-01-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_match_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='users',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
