# Generated by Django 2.1.5 on 2019-01-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='available',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='map',
            field=models.CharField(choices=[('Erangel', 'Erangel'), ('Miramar', 'Miramar'), ('Sanhok', 'Sanhok'), ('Vikendi', 'Vikendi')], default='Erangel', max_length=8),
        ),
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Squad', 'Squad')], default='Solo', max_length=6),
        ),
        migrations.AlterField(
            model_name='match',
            name='version',
            field=models.CharField(choices=[('TPP', 'TPP'), ('FPP', 'FPP')], default='TPP', max_length=4),
        ),
    ]
