# Generated by Django 2.1.5 on 2019-01-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190119_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
