# Generated by Django 2.1.5 on 2019-01-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
