# Generated by Django 2.1.3 on 2019-01-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='amount_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='fname',
            field=models.CharField(default=12, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='lname',
            field=models.CharField(default=12, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='match_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='phone',
            field=models.CharField(default=12, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='total_kills',
            field=models.IntegerField(default=0),
        ),
    ]
