# Generated by Django 2.1.3 on 2019-01-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20190120_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
