# Generated by Django 2.1.5 on 2019-01-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_match_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreePayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.IntegerField()),
                ('users', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='entry',
        ),
        migrations.AlterField(
            model_name='match',
            name='pay',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='users',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
