# Generated by Django 2.1.5 on 2019-01-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20190130_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='entry',
            field=models.IntegerField(default=0),
        ),
    ]
